concurrent = 1
check_interval = 0

[[runners]]
  name = "docker-runner"
  url = "http://gitlab.local/"
  token = "YOUR_RUNNER_TOKEN"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
  [runners.docker]
    tls_verify = false
    image = "python:3.11"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
  listen_address = ":9252"

