global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gitlab'
    static_configs:
      - targets: ['gitlab-exporter:9252']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx:9113']

